import { z } from "zod";
import {
  EVALUATION_CATEGORIES,
  type EvaluationCategoryId,
  type ResumeEvaluationReport,
} from "@/lib/resumeEvaluation";

const issueSchema = z.object({
  severity: z.enum(["critical", "recommendation", "nice"]),
  title: z.string().min(1),
  detail: z.string().min(1),
  section: z.string().optional(),
});

const categoryScoreSchema = z.object({
  id: z.enum(
    EVALUATION_CATEGORIES.map((category) => category.id) as [
      EvaluationCategoryId,
      ...EvaluationCategoryId[],
    ],
  ),
  label: z.string().min(1),
  score: z.number(),
  summary: z.string().min(1),
});

const keywordCoverageSchema = z.object({
  keyword: z.string().min(1),
  status: z.enum(["covered", "missing", "weak", "notEvaluated"]),
  placement: z.string().optional(),
  evidence: z.string().optional(),
});

const bulletRewriteSchema = z.object({
  original: z.string().min(1),
  rewrite: z.string().min(1),
  reason: z.string().min(1),
});

const aiReportSchema = z.object({
  overallScore: z.number(),
  categoryScores: z.array(categoryScoreSchema),
  criticalIssues: z.array(issueSchema),
  recommendations: z.array(issueSchema),
  niceToHaves: z.array(issueSchema),
  keywordCoverage: z.array(keywordCoverageSchema),
  missingKeywords: z.array(z.string()),
  suggestedPlacements: z.array(z.string()),
  bulletRewrites: z.array(bulletRewriteSchema),
  recruiterSummary: z.string(),
  interviewQuestions: z.array(z.string()),
  skillsGap: z.array(z.string()),
});

function clampScore(score: number) {
  return Math.max(0, Math.min(100, Math.round(score)));
}

function cleanJson(rawText: string) {
  let cleaned = rawText.trim();
  if (cleaned.startsWith("```")) {
    cleaned = cleaned
      .replace(/^```(?:json)?/i, "")
      .replace(/```$/, "")
      .trim();
  }
  return cleaned;
}

function normalizeCategories(categories: ResumeEvaluationReport["categoryScores"]) {
  const byId = new Map(categories.map((category) => [category.id, category]));
  return EVALUATION_CATEGORIES.map((category) => {
    const existing = byId.get(category.id);
    return {
      id: category.id,
      label: existing?.label || category.label,
      score: clampScore(existing?.score ?? 60),
      summary: existing?.summary || "Not evaluated in detail.",
    };
  });
}

export function parseEvaluationResponse(
  rawText: string,
  hasJobDescription: boolean,
): ResumeEvaluationReport {
  const parsed = aiReportSchema.parse(JSON.parse(cleanJson(rawText)));
  return {
    ...parsed,
    overallScore: clampScore(parsed.overallScore),
    categoryScores: normalizeCategories(parsed.categoryScores),
    metadata: {
      hasJobDescription,
      generatedAt: new Date().toISOString(),
      source: "ai",
    },
  };
}

export function buildEvaluationPrompt(markdown: string, jobDescription: string) {
  const hasJd = jobDescription.trim().length > 0;
  const categoryList = EVALUATION_CATEGORIES.map(
    (category) => `- ${category.id}: ${category.label}`,
  ).join("\n");

  const system = `You are a senior recruiter, hiring manager, resume strategist, ATS evaluator, and Markdown quality reviewer.

Evaluate the candidate resume using the exact 13-category framework below. Be specific, evidence-backed, and practical.

Rules:
- Return ONLY valid JSON. No markdown fences, commentary, or trailing text.
- All assessment must be generated by the model from the supplied resume and optional job description only.
- Do not invent candidate experience, metrics, employers, degrees, dates, or skills.
- If a job description is not provided, mark JD-specific coverage as notEvaluated and do not fabricate target alignment.
- Every critical issue should cite a section, bullet, or concrete evidence when possible.
- Bullet rewrites must be Markdown bullets ready to copy. Use placeholders like [X]% only when the original lacks real metrics.
- Keep arrays concise: up to 6 critical issues, 8 recommendations, 6 nice-to-haves, 12 keyword coverage rows, 5 rewrites, 6 interview questions, 8 skills gaps.
- Scores must be integers from 0 to 100.

Categories:
${categoryList}

Required JSON shape:
{
  "overallScore": 0,
  "categoryScores": [{"id":"keywordAlignment","label":"Keyword & JD Alignment","score":0,"summary":"..."}],
  "criticalIssues": [{"severity":"critical","title":"...","detail":"...","section":"..."}],
  "recommendations": [{"severity":"recommendation","title":"...","detail":"...","section":"..."}],
  "niceToHaves": [{"severity":"nice","title":"...","detail":"...","section":"..."}],
  "keywordCoverage": [{"keyword":"...","status":"covered|missing|weak|notEvaluated","placement":"...","evidence":"..."}],
  "missingKeywords": ["..."],
  "suggestedPlacements": ["..."],
  "bulletRewrites": [{"original":"- ...","rewrite":"- ...","reason":"..."}],
  "recruiterSummary": "...",
  "interviewQuestions": ["..."],
  "skillsGap": ["..."]
}`;

  const user = `RESUME MARKDOWN:
${markdown}

JOB DESCRIPTION STATUS: ${hasJd ? "Provided" : "Not provided"}
${hasJd ? `TARGET JOB DESCRIPTION:\n${jobDescription}` : ""}`;

  return { system, user };
}
